services:
  backend:
    build:
      context: ./fast_api
    image: vicksinhaler/my-backend-image:latest
    container_name: backend-container
    ports:
      - "8000:8000"
    networks:
      - my-network
    environment:
      # FastAPI Configuration
      FASTAPI_URL: ${FASTAPI_URL}
 
      # Snowflake Configuration
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
      SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE}
      SNOWFLAKE_SCHEMA: ${SNOWFLAKE_SCHEMA}
 
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}
 
      # Pinecone Configuration
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
      PINECONE_INDEX_NAME: ${PINECONE_INDEX_NAME}
      DIMENSION: ${DIMENSION}
      METRIC: ${METRIC}
 
      # YouTube API Configuration
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
 
      # Tavily Configuration
      TAVILY_API_KEY: ${TAVILY_API_KEY}
 
  frontend:
    build:
      context: ./Streamlit
    image: vicksinhaler/my-frontend-image:latest
    container_name: frontend-container
    ports:
      - "8501:8501"
    networks:
      - my-network
    environment:
      # Frontend Configuration
      FASTAPI_URL: ${FASTAPI_URL}  # Corrected FastAPI URL
 
networks:
  my-network:
    driver: bridge
